import copy
import time

import aiofiles

from .. import *
from .image import generate_frosted_card, tricolor_gradient_prism_plus
from .maimai_best_50 import *
from .maimaidx_music import Music, mai


def _generate_prism_plus_bg(height: int, separator_height: int) -> Image.Image:
    im = tricolor_gradient_prism_plus(1400, height)
    im.alpha_composite(Image.open(maimaidir / 'aurora.png').convert('RGBA'))
    im.alpha_composite(Image.open(maimaidir / 'bg_shines.png').convert('RGBA'), (11, 6))
    im.alpha_composite(Image.open(maimaidir / 'rainbow.png').convert('RGBA'), (318, height - 545))
    im.alpha_composite(Image.open(maimaidir / 'rainbow_bottom.png').convert('RGBA'), (122, height - 305))
    pattern = Image.open(maimaidir / 'pattern.png').convert('RGBA')
    for h in range((height // 358) + 1):
        im.alpha_composite(pattern, (0, (358 + 7) * h))
    separator = maimaidir / 'separator.png'
    if separator.exists():
        im.alpha_composite(Image.open(separator).convert('RGBA'), (100, separator_height))
    return im


async def update_rating_table() -> str:
    """Update generated rating tables with the PRiSM PLUS layout."""
    try:
        ratingdir.mkdir(parents=True, exist_ok=True)
        diff_bg = [
            Image.open(maimaidir / 'border_basic.png').convert('RGBA'),
            Image.open(maimaidir / 'border_advanced.png').convert('RGBA'),
            Image.open(maimaidir / 'border_expert.png').convert('RGBA'),
            Image.open(maimaidir / 'border_master.png').convert('RGBA'),
            Image.open(maimaidir / 'border_remaster.png').convert('RGBA'),
        ]
        if maiApi.config.saveinmem and not ScoreBaseImage.aurora_bg:
            ScoreBaseImage._load_image()
        sbi = ScoreBaseImage if maiApi.config.saveinmem else ScoreBaseImage()
        atime = 0

        for lv in levelList[6:]:
            start_time = time.time()
            lvlist = mai.total_level_data[lv]
            grid_step = 85
            start_x = 140
            current_y = 450

            for songs in lvlist.values():
                if not songs:
                    continue
                rows = (len(songs) - 1) // 14 + 1
                current_y += rows * grid_step + 30

            height = current_y + 230
            im = generate_frosted_card(_generate_prism_plus_bg(height, 360), (50, 404, 1350, current_y))

            dr = ImageDraw.Draw(im)
            ts = DrawText(dr, TBFONT)
            ts.draw(
                700,
                height - 75,
                30,
                f'Designed by Yuri-YuzuChaN & BlueDeer233. Generated by {get_botname()} BOT',
                sbi.text_color,
                'mm',
            )

            y = 450
            for ds, songs in lvlist.items():
                if not songs:
                    continue
                level_label = f".{str(ds).split('.')[-1]}" if "." in str(ds) else str(ds)
                ts.draw(70, y + 35, 40, level_label, sbi.text_color, 'lm', 4, (255, 255, 255, 255))
                max_row = 0
                for num, music in enumerate(songs):
                    row, col = divmod(num, 14)
                    max_row = max(max_row, row)
                    x = start_x + col * grid_step
                    cover_y = y + row * grid_step
                    im.alpha_composite(Image.open(music_picture(music.id)).resize((75, 75)), (x, cover_y))
                    im.alpha_composite(diff_bg[int(music.lv)], (x - 5, cover_y - 5))
                    ts.draw(x + 56, cover_y + 4, 13, music.id, sbi.t_color[int(music.lv)], 'mm')
                y += (max_row + 1) * grid_step + 30

            by = BytesIO()
            im.save(by, 'PNG')
            async with aiofiles.open(ratingdir / f'{lv}.png', 'wb') as f:
                await f.write(by.getbuffer())
            elapsed = int(time.time() - start_time)
            atime += elapsed
            log.info(f'lv.{lv} 定数表更新完成，耗时：{elapsed}s')

        log.info(f'定数表更新完成，共耗时{atime}s')
        return f'定数表更新完成，共耗时{atime}s'
    except Exception as e:
        log.error(traceback.format_exc())
        return f'定数表更新失败，Error: {e}'


async def _update_rating_table_legacy() -> str:
    """更新定数表"""
    try:
        ratingdir.mkdir(parents=True, exist_ok=True)
        dx = Image.open(maimaidir / 'DX.png').convert('RGBA').resize((44, 16))
        diff = [Image.new('RGBA', (75, 16), color) for color in ScoreBaseImage.bg_color]
        if maiApi.config.saveinmem and not ScoreBaseImage.aurora_bg:
            ScoreBaseImage._load_image()
        sbi = ScoreBaseImage if maiApi.config.saveinmem else ScoreBaseImage()
        atime = 0
        for lv in levelList[6:]:
            _otime = time.time()
            picname = ratingdir / f'{lv}.png'
            lvlist = mai.total_level_data[lv]
            lines = 0
            for _lv in lvlist:
                musicnum = len(lvlist[_lv])
                if musicnum == 0:
                    r = 1
                else:
                    remainder = musicnum % 14
                    r = (musicnum // 14) + (1 if remainder else 0)
                lines += r

            if '+' in lv:
                f = 4
            elif lv == '6':
                f = 10
            else:
                f = 8

            linesheight = 85 * lines
            """
            `85` 为曲绘高度 `80` + 间隔 `5`
            `lines` 为行数
            """
            
            width, height = 1400, 325 + f * 20 + linesheight
            """
            `325` 为顶部文字和底部图片高度 + 上下间隔高度
            `f * 20` 为等级数量 `f` * 等级间隔 `20`
            `linesheight` 为各等级曲绘和间隔总和高度
            """
            
            im = _generate_prism_plus_bg(height, 360)

            dr = ImageDraw.Draw(im)
            sy = DrawText(dr, SIYUAN)
            ts = DrawText(dr, TBFONT)
            im.alpha_composite(Image.open(themepicdir / 'design.png'), (200, height - 113))
            sy.draw(
                700, 
                height - 70, 
                22, 
                f'Designed by Yuri-YuzuChaN & BlueDeer233. Generated by {get_botname()} BOT', 
                sbi.text_color, 
                'mm'
            )
            y = 100
            for _lv in lvlist: 
                x = 160
                y += 20
                level_label = f".{str(_lv).split('.')[-1]}" if "." in str(_lv) else str(_lv)
                ts.draw(88, y + 120, 35, level_label, sbi.text_color, 'mm', 4, (255, 255, 255, 255))
                for num, music in enumerate(lvlist[_lv]):
                    if num % 14 == 0:
                        x = 160
                        y += 85
                    else:
                        x += 85
                    cover = Image.open(music_picture(music.id)).resize((75, 75))
                    im.alpha_composite(cover, (x, y))
                    if music.type == 'DX':
                        im.alpha_composite(dx, (x + 31, y))
                    im.alpha_composite(diff[int(music.lv)], (x, y + 59))
                    ts.draw(x + 37, y + 67, 13, music.id, sbi.t_color[int(music.lv)], 'mm')
                if not lvlist[_lv]:
                    y += 85

            by = BytesIO()
            im.save(by, 'PNG')
            async with aiofiles.open(picname, 'wb') as f:
                await f.write(by.getbuffer())
            _ntime = int(time.time() - _otime)
            atime += _ntime
            log.info(f'lv.{lv} 定数表更新完成，耗时：{_ntime}s')
        log.info(f'定数表更新完成，共耗时{atime}s')
        return f'定数表更新完成，共耗时{atime}s'
    except Exception as e:
        log.error(traceback.format_exc())
        return f'定数表更新失败，Error: {e}'


async def update_plate_table() -> str:
    """更新完成表"""
    try:
        platedir.mkdir(parents=True, exist_ok=True)
        version = list(_ for _ in plate_to_dx_version.keys())[1:]
        # version.append('霸')
        # version.append('舞')
        id_bg = Image.open(maimaidir / 'border_table_base.png')
        rlv: Dict[str, List[Music]] = {}
        for _ in list(reversed(levelList)):
            rlv[_] = []
        if maiApi.config.saveinmem and not ScoreBaseImage.aurora_bg:
            ScoreBaseImage._load_image()
        sbi = ScoreBaseImage if maiApi.config.saveinmem else ScoreBaseImage()
        for _v in version:
            if _v in platecn:
                _v = platecn[_v]
            ver, _ver = version_map.get(_v, ([plate_to_dx_version.get(_v)], _v))

            if _ver not in mai.total_plate_id_list:
                available = '，'.join(mai.total_plate_id_list.keys())
                raise KeyError(f'完成表版本「{_ver}」不存在，可用版本：{available}')

            music_id_list = mai.total_plate_id_list[_ver]
            music = mai.total_list.by_id_list(music_id_list)
            ralv = copy.deepcopy(rlv)

            for m in music:
                ralv[m.level[3]].append(m)

            grid_step = 96
            start_x = 180
            row_count = 12
            current_y = 490
            for songs in ralv.values():
                if not songs:
                    continue
                rows = (len(songs) - 1) // row_count + 1
                current_y += rows * grid_step + 30

            width, height = 1400, current_y + 180

            im = generate_frosted_card(_generate_prism_plus_bg(height, 400), (50, 444, 1350, current_y))
            
            dr = ImageDraw.Draw(im)
            ts = DrawText(dr, TBFONT)
            sy = DrawText(dr, SIYUAN)
            sy.draw(
                700, 
                height - 75,
                30,
                f'Designed by Yuri-YuzuChaN & BlueDeer233. Generated by {get_botname()} BOT',
                sbi.text_color, 
                'mm'
            )
            y = 490
            for r in ralv:
                if _v in ['霸', '舞']:
                    ralv[r].sort(key=lambda x: x.ds[-1], reverse=True)
                else:
                    ralv[r].sort(key=lambda x: x.ds[3], reverse=True)
                if not ralv[r]:
                    continue
                sy.draw(72, y + 40, 40, r, sbi.text_color, 'lm', 4, (255, 255, 255, 255))
                max_row = 0
                for num, music in enumerate(ralv[r]):
                    row, col = divmod(num, row_count)
                    max_row = max(max_row, row)
                    x = start_x + col * grid_step
                    _y = y + row * grid_step
                    cover = music_picture(music.id)
                    im.alpha_composite(Image.open(cover).resize((80, 80)), (x, _y))
                    im.alpha_composite(id_bg, (x - 5, _y - 5))
                    ts.draw(x + 56, _y + 4, 16, music.id, (255, 255, 255, 255), 'mm')
                y += (max_row + 1) * grid_step + 30

            by = BytesIO()
            im.save(by, 'PNG')
            async with aiofiles.open(platedir / f'{_v}.png', 'wb') as f:
                await f.write(by.getbuffer())
            log.info(f'{_v}代牌子更新完成')
        return f'完成表更新完成'
    except Exception as e:
        log.error(traceback.format_exc())
        return f'完成表更新失败，Error: {e}'
